/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetCharactersCharacterIdChatChannelsOperator = factory(root.EveSwaggerInterface.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetCharactersCharacterIdChatChannelsOperator model module.
   * @module model/GetCharactersCharacterIdChatChannelsOperator
   * @version 0.5.0
   */

  /**
   * Constructs a new <code>GetCharactersCharacterIdChatChannelsOperator</code>.
   * operator object
   * @alias module:model/GetCharactersCharacterIdChatChannelsOperator
   * @class
   * @param accessorId {Number} ID of a channel operator
   * @param accessorType {module:model/GetCharactersCharacterIdChatChannelsOperator.AccessorTypeEnum} accessor_type string
   */
  var exports = function(accessorId, accessorType) {
    var _this = this;

    _this['accessor_id'] = accessorId;
    _this['accessor_type'] = accessorType;
  };

  /**
   * Constructs a <code>GetCharactersCharacterIdChatChannelsOperator</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCharactersCharacterIdChatChannelsOperator} obj Optional instance to populate.
   * @return {module:model/GetCharactersCharacterIdChatChannelsOperator} The populated <code>GetCharactersCharacterIdChatChannelsOperator</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('accessor_id')) {
        obj['accessor_id'] = ApiClient.convertToType(data['accessor_id'], 'Number');
      }
      if (data.hasOwnProperty('accessor_type')) {
        obj['accessor_type'] = ApiClient.convertToType(data['accessor_type'], 'String');
      }
    }
    return obj;
  }

  /**
   * ID of a channel operator
   * @member {Number} accessor_id
   */
  exports.prototype['accessor_id'] = undefined;
  /**
   * accessor_type string
   * @member {module:model/GetCharactersCharacterIdChatChannelsOperator.AccessorTypeEnum} accessor_type
   */
  exports.prototype['accessor_type'] = undefined;


  /**
   * Allowed values for the <code>accessor_type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.AccessorTypeEnum = {
    /**
     * value: "character"
     * @const
     */
    "character": "character",
    /**
     * value: "corporation"
     * @const
     */
    "corporation": "corporation",
    /**
     * value: "alliance"
     * @const
     */
    "alliance": "alliance"  };


  return exports;
}));


