/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetCharactersCharacterIdChatChannelsAllowed', 'model/GetCharactersCharacterIdChatChannelsBlocked', 'model/GetCharactersCharacterIdChatChannelsMuted', 'model/GetCharactersCharacterIdChatChannelsOperator'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GetCharactersCharacterIdChatChannelsAllowed'), require('./GetCharactersCharacterIdChatChannelsBlocked'), require('./GetCharactersCharacterIdChatChannelsMuted'), require('./GetCharactersCharacterIdChatChannelsOperator'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetCharactersCharacterIdChatChannels200Ok = factory(root.EveSwaggerInterface.ApiClient, root.EveSwaggerInterface.GetCharactersCharacterIdChatChannelsAllowed, root.EveSwaggerInterface.GetCharactersCharacterIdChatChannelsBlocked, root.EveSwaggerInterface.GetCharactersCharacterIdChatChannelsMuted, root.EveSwaggerInterface.GetCharactersCharacterIdChatChannelsOperator);
  }
}(this, function(ApiClient, GetCharactersCharacterIdChatChannelsAllowed, GetCharactersCharacterIdChatChannelsBlocked, GetCharactersCharacterIdChatChannelsMuted, GetCharactersCharacterIdChatChannelsOperator) {
  'use strict';




  /**
   * The GetCharactersCharacterIdChatChannels200Ok model module.
   * @module model/GetCharactersCharacterIdChatChannels200Ok
   * @version 0.5.0
   */

  /**
   * Constructs a new <code>GetCharactersCharacterIdChatChannels200Ok</code>.
   * 200 ok object
   * @alias module:model/GetCharactersCharacterIdChatChannels200Ok
   * @class
   * @param allowed {Array.<module:model/GetCharactersCharacterIdChatChannelsAllowed>} allowed array
   * @param blocked {Array.<module:model/GetCharactersCharacterIdChatChannelsBlocked>} blocked array
   * @param channelId {Number} Unique channel ID. Always negative for player-created channels. Permanent (CCP created) channels have a positive ID, but don't appear in the API
   * @param comparisonKey {String} Normalized, unique string used to compare channel names
   * @param hasPassword {Boolean} Whether this is a password protected channel
   * @param motd {String} Message of the day for this channel
   * @param muted {Array.<module:model/GetCharactersCharacterIdChatChannelsMuted>} muted array
   * @param name {String} Displayed name of channel
   * @param operators {Array.<module:model/GetCharactersCharacterIdChatChannelsOperator>} operators array
   * @param ownerId {Number} owner_id integer
   */
  var exports = function(allowed, blocked, channelId, comparisonKey, hasPassword, motd, muted, name, operators, ownerId) {
    var _this = this;

    _this['allowed'] = allowed;
    _this['blocked'] = blocked;
    _this['channel_id'] = channelId;
    _this['comparison_key'] = comparisonKey;
    _this['has_password'] = hasPassword;
    _this['motd'] = motd;
    _this['muted'] = muted;
    _this['name'] = name;
    _this['operators'] = operators;
    _this['owner_id'] = ownerId;
  };

  /**
   * Constructs a <code>GetCharactersCharacterIdChatChannels200Ok</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCharactersCharacterIdChatChannels200Ok} obj Optional instance to populate.
   * @return {module:model/GetCharactersCharacterIdChatChannels200Ok} The populated <code>GetCharactersCharacterIdChatChannels200Ok</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('allowed')) {
        obj['allowed'] = ApiClient.convertToType(data['allowed'], [GetCharactersCharacterIdChatChannelsAllowed]);
      }
      if (data.hasOwnProperty('blocked')) {
        obj['blocked'] = ApiClient.convertToType(data['blocked'], [GetCharactersCharacterIdChatChannelsBlocked]);
      }
      if (data.hasOwnProperty('channel_id')) {
        obj['channel_id'] = ApiClient.convertToType(data['channel_id'], 'Number');
      }
      if (data.hasOwnProperty('comparison_key')) {
        obj['comparison_key'] = ApiClient.convertToType(data['comparison_key'], 'String');
      }
      if (data.hasOwnProperty('has_password')) {
        obj['has_password'] = ApiClient.convertToType(data['has_password'], 'Boolean');
      }
      if (data.hasOwnProperty('motd')) {
        obj['motd'] = ApiClient.convertToType(data['motd'], 'String');
      }
      if (data.hasOwnProperty('muted')) {
        obj['muted'] = ApiClient.convertToType(data['muted'], [GetCharactersCharacterIdChatChannelsMuted]);
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('operators')) {
        obj['operators'] = ApiClient.convertToType(data['operators'], [GetCharactersCharacterIdChatChannelsOperator]);
      }
      if (data.hasOwnProperty('owner_id')) {
        obj['owner_id'] = ApiClient.convertToType(data['owner_id'], 'Number');
      }
    }
    return obj;
  }

  /**
   * allowed array
   * @member {Array.<module:model/GetCharactersCharacterIdChatChannelsAllowed>} allowed
   */
  exports.prototype['allowed'] = undefined;
  /**
   * blocked array
   * @member {Array.<module:model/GetCharactersCharacterIdChatChannelsBlocked>} blocked
   */
  exports.prototype['blocked'] = undefined;
  /**
   * Unique channel ID. Always negative for player-created channels. Permanent (CCP created) channels have a positive ID, but don't appear in the API
   * @member {Number} channel_id
   */
  exports.prototype['channel_id'] = undefined;
  /**
   * Normalized, unique string used to compare channel names
   * @member {String} comparison_key
   */
  exports.prototype['comparison_key'] = undefined;
  /**
   * Whether this is a password protected channel
   * @member {Boolean} has_password
   */
  exports.prototype['has_password'] = undefined;
  /**
   * Message of the day for this channel
   * @member {String} motd
   */
  exports.prototype['motd'] = undefined;
  /**
   * muted array
   * @member {Array.<module:model/GetCharactersCharacterIdChatChannelsMuted>} muted
   */
  exports.prototype['muted'] = undefined;
  /**
   * Displayed name of channel
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * operators array
   * @member {Array.<module:model/GetCharactersCharacterIdChatChannelsOperator>} operators
   */
  exports.prototype['operators'] = undefined;
  /**
   * owner_id integer
   * @member {Number} owner_id
   */
  exports.prototype['owner_id'] = undefined;



  return exports;
}));


