/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetUniverseSystemKills200Ok = factory(root.EveSwaggerInterface.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetUniverseSystemKills200Ok model module.
   * @module model/GetUniverseSystemKills200Ok
   * @version 0.5.0
   */

  /**
   * Constructs a new <code>GetUniverseSystemKills200Ok</code>.
   * 200 ok object
   * @alias module:model/GetUniverseSystemKills200Ok
   * @class
   * @param npcKills {Number} Number of NPC ships killed in this system
   * @param podKills {Number} Number of pods killed in this system
   * @param shipKills {Number} Number of player and NPC ships killed in this system
   * @param systemId {Number} system_id integer
   */
  var exports = function(npcKills, podKills, shipKills, systemId) {
    var _this = this;

    _this['npc_kills'] = npcKills;
    _this['pod_kills'] = podKills;
    _this['ship_kills'] = shipKills;
    _this['system_id'] = systemId;
  };

  /**
   * Constructs a <code>GetUniverseSystemKills200Ok</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetUniverseSystemKills200Ok} obj Optional instance to populate.
   * @return {module:model/GetUniverseSystemKills200Ok} The populated <code>GetUniverseSystemKills200Ok</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('npc_kills')) {
        obj['npc_kills'] = ApiClient.convertToType(data['npc_kills'], 'Number');
      }
      if (data.hasOwnProperty('pod_kills')) {
        obj['pod_kills'] = ApiClient.convertToType(data['pod_kills'], 'Number');
      }
      if (data.hasOwnProperty('ship_kills')) {
        obj['ship_kills'] = ApiClient.convertToType(data['ship_kills'], 'Number');
      }
      if (data.hasOwnProperty('system_id')) {
        obj['system_id'] = ApiClient.convertToType(data['system_id'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Number of NPC ships killed in this system
   * @member {Number} npc_kills
   */
  exports.prototype['npc_kills'] = undefined;
  /**
   * Number of pods killed in this system
   * @member {Number} pod_kills
   */
  exports.prototype['pod_kills'] = undefined;
  /**
   * Number of player and NPC ships killed in this system
   * @member {Number} ship_kills
   */
  exports.prototype['ship_kills'] = undefined;
  /**
   * system_id integer
   * @member {Number} system_id
   */
  exports.prototype['system_id'] = undefined;



  return exports;
}));


