/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveSwaggerInterface);
  }
}(this, function(expect, EveSwaggerInterface) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EveSwaggerInterface.GetCharactersCharacterIdPlanetsPlanetIdRoute();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetCharactersCharacterIdPlanetsPlanetIdRoute', function() {
    it('should create an instance of GetCharactersCharacterIdPlanetsPlanetIdRoute', function() {
      // uncomment below and update the code to test GetCharactersCharacterIdPlanetsPlanetIdRoute
      //var instane = new EveSwaggerInterface.GetCharactersCharacterIdPlanetsPlanetIdRoute();
      //expect(instance).to.be.a(EveSwaggerInterface.GetCharactersCharacterIdPlanetsPlanetIdRoute);
    });

    it('should have the property contentTypeId (base name: "content_type_id")', function() {
      // uncomment below and update the code to test the property contentTypeId
      //var instane = new EveSwaggerInterface.GetCharactersCharacterIdPlanetsPlanetIdRoute();
      //expect(instance).to.be();
    });

    it('should have the property destinationPinId (base name: "destination_pin_id")', function() {
      // uncomment below and update the code to test the property destinationPinId
      //var instane = new EveSwaggerInterface.GetCharactersCharacterIdPlanetsPlanetIdRoute();
      //expect(instance).to.be();
    });

    it('should have the property quantity (base name: "quantity")', function() {
      // uncomment below and update the code to test the property quantity
      //var instane = new EveSwaggerInterface.GetCharactersCharacterIdPlanetsPlanetIdRoute();
      //expect(instance).to.be();
    });

    it('should have the property routeId (base name: "route_id")', function() {
      // uncomment below and update the code to test the property routeId
      //var instane = new EveSwaggerInterface.GetCharactersCharacterIdPlanetsPlanetIdRoute();
      //expect(instance).to.be();
    });

    it('should have the property sourcePinId (base name: "source_pin_id")', function() {
      // uncomment below and update the code to test the property sourcePinId
      //var instane = new EveSwaggerInterface.GetCharactersCharacterIdPlanetsPlanetIdRoute();
      //expect(instance).to.be();
    });

    it('should have the property waypoints (base name: "waypoints")', function() {
      // uncomment below and update the code to test the property waypoints
      //var instane = new EveSwaggerInterface.GetCharactersCharacterIdPlanetsPlanetIdRoute();
      //expect(instance).to.be();
    });

  });

}));
