/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveSwaggerInterface);
  }
}(this, function(expect, EveSwaggerInterface) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EveSwaggerInterface.GetCharactersCharacterIdMail200Ok();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetCharactersCharacterIdMail200Ok', function() {
    it('should create an instance of GetCharactersCharacterIdMail200Ok', function() {
      // uncomment below and update the code to test GetCharactersCharacterIdMail200Ok
      //var instane = new EveSwaggerInterface.GetCharactersCharacterIdMail200Ok();
      //expect(instance).to.be.a(EveSwaggerInterface.GetCharactersCharacterIdMail200Ok);
    });

    it('should have the property from (base name: "from")', function() {
      // uncomment below and update the code to test the property from
      //var instane = new EveSwaggerInterface.GetCharactersCharacterIdMail200Ok();
      //expect(instance).to.be();
    });

    it('should have the property isRead (base name: "is_read")', function() {
      // uncomment below and update the code to test the property isRead
      //var instane = new EveSwaggerInterface.GetCharactersCharacterIdMail200Ok();
      //expect(instance).to.be();
    });

    it('should have the property labels (base name: "labels")', function() {
      // uncomment below and update the code to test the property labels
      //var instane = new EveSwaggerInterface.GetCharactersCharacterIdMail200Ok();
      //expect(instance).to.be();
    });

    it('should have the property mailId (base name: "mail_id")', function() {
      // uncomment below and update the code to test the property mailId
      //var instane = new EveSwaggerInterface.GetCharactersCharacterIdMail200Ok();
      //expect(instance).to.be();
    });

    it('should have the property recipients (base name: "recipients")', function() {
      // uncomment below and update the code to test the property recipients
      //var instane = new EveSwaggerInterface.GetCharactersCharacterIdMail200Ok();
      //expect(instance).to.be();
    });

    it('should have the property subject (base name: "subject")', function() {
      // uncomment below and update the code to test the property subject
      //var instane = new EveSwaggerInterface.GetCharactersCharacterIdMail200Ok();
      //expect(instance).to.be();
    });

    it('should have the property timestamp (base name: "timestamp")', function() {
      // uncomment below and update the code to test the property timestamp
      //var instane = new EveSwaggerInterface.GetCharactersCharacterIdMail200Ok();
      //expect(instance).to.be();
    });

  });

}));
