/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveSwaggerInterface);
  }
}(this, function(expect, EveSwaggerInterface) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EveSwaggerInterface.GetCorporationsCorporationIdStructures200Ok();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetCorporationsCorporationIdStructures200Ok', function() {
    it('should create an instance of GetCorporationsCorporationIdStructures200Ok', function() {
      // uncomment below and update the code to test GetCorporationsCorporationIdStructures200Ok
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdStructures200Ok();
      //expect(instance).to.be.a(EveSwaggerInterface.GetCorporationsCorporationIdStructures200Ok);
    });

    it('should have the property corporationId (base name: "corporation_id")', function() {
      // uncomment below and update the code to test the property corporationId
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdStructures200Ok();
      //expect(instance).to.be();
    });

    it('should have the property currentVul (base name: "current_vul")', function() {
      // uncomment below and update the code to test the property currentVul
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdStructures200Ok();
      //expect(instance).to.be();
    });

    it('should have the property fuelExpires (base name: "fuel_expires")', function() {
      // uncomment below and update the code to test the property fuelExpires
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdStructures200Ok();
      //expect(instance).to.be();
    });

    it('should have the property nextVul (base name: "next_vul")', function() {
      // uncomment below and update the code to test the property nextVul
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdStructures200Ok();
      //expect(instance).to.be();
    });

    it('should have the property profileId (base name: "profile_id")', function() {
      // uncomment below and update the code to test the property profileId
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdStructures200Ok();
      //expect(instance).to.be();
    });

    it('should have the property services (base name: "services")', function() {
      // uncomment below and update the code to test the property services
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdStructures200Ok();
      //expect(instance).to.be();
    });

    it('should have the property stateTimerEnd (base name: "state_timer_end")', function() {
      // uncomment below and update the code to test the property stateTimerEnd
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdStructures200Ok();
      //expect(instance).to.be();
    });

    it('should have the property stateTimerStart (base name: "state_timer_start")', function() {
      // uncomment below and update the code to test the property stateTimerStart
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdStructures200Ok();
      //expect(instance).to.be();
    });

    it('should have the property structureId (base name: "structure_id")', function() {
      // uncomment below and update the code to test the property structureId
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdStructures200Ok();
      //expect(instance).to.be();
    });

    it('should have the property systemId (base name: "system_id")', function() {
      // uncomment below and update the code to test the property systemId
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdStructures200Ok();
      //expect(instance).to.be();
    });

    it('should have the property typeId (base name: "type_id")', function() {
      // uncomment below and update the code to test the property typeId
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdStructures200Ok();
      //expect(instance).to.be();
    });

    it('should have the property unanchorsAt (base name: "unanchors_at")', function() {
      // uncomment below and update the code to test the property unanchorsAt
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdStructures200Ok();
      //expect(instance).to.be();
    });

  });

}));
