/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveSwaggerInterface);
  }
}(this, function(expect, EveSwaggerInterface) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EveSwaggerInterface.GetCorporationsCorporationIdOk();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetCorporationsCorporationIdOk', function() {
    it('should create an instance of GetCorporationsCorporationIdOk', function() {
      // uncomment below and update the code to test GetCorporationsCorporationIdOk
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdOk();
      //expect(instance).to.be.a(EveSwaggerInterface.GetCorporationsCorporationIdOk);
    });

    it('should have the property allianceId (base name: "alliance_id")', function() {
      // uncomment below and update the code to test the property allianceId
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdOk();
      //expect(instance).to.be();
    });

    it('should have the property ceoId (base name: "ceo_id")', function() {
      // uncomment below and update the code to test the property ceoId
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdOk();
      //expect(instance).to.be();
    });

    it('should have the property corporationDescription (base name: "corporation_description")', function() {
      // uncomment below and update the code to test the property corporationDescription
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdOk();
      //expect(instance).to.be();
    });

    it('should have the property corporationName (base name: "corporation_name")', function() {
      // uncomment below and update the code to test the property corporationName
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdOk();
      //expect(instance).to.be();
    });

    it('should have the property creationDate (base name: "creation_date")', function() {
      // uncomment below and update the code to test the property creationDate
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdOk();
      //expect(instance).to.be();
    });

    it('should have the property creatorId (base name: "creator_id")', function() {
      // uncomment below and update the code to test the property creatorId
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdOk();
      //expect(instance).to.be();
    });

    it('should have the property faction (base name: "faction")', function() {
      // uncomment below and update the code to test the property faction
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdOk();
      //expect(instance).to.be();
    });

    it('should have the property memberCount (base name: "member_count")', function() {
      // uncomment below and update the code to test the property memberCount
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdOk();
      //expect(instance).to.be();
    });

    it('should have the property taxRate (base name: "tax_rate")', function() {
      // uncomment below and update the code to test the property taxRate
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdOk();
      //expect(instance).to.be();
    });

    it('should have the property ticker (base name: "ticker")', function() {
      // uncomment below and update the code to test the property ticker
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdOk();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instane = new EveSwaggerInterface.GetCorporationsCorporationIdOk();
      //expect(instance).to.be();
    });

  });

}));
