/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveSwaggerInterface);
  }
}(this, function(expect, EveSwaggerInterface) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EveSwaggerInterface.GetDogmaAttributesAttributeIdOk();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetDogmaAttributesAttributeIdOk', function() {
    it('should create an instance of GetDogmaAttributesAttributeIdOk', function() {
      // uncomment below and update the code to test GetDogmaAttributesAttributeIdOk
      //var instane = new EveSwaggerInterface.GetDogmaAttributesAttributeIdOk();
      //expect(instance).to.be.a(EveSwaggerInterface.GetDogmaAttributesAttributeIdOk);
    });

    it('should have the property attributeId (base name: "attribute_id")', function() {
      // uncomment below and update the code to test the property attributeId
      //var instane = new EveSwaggerInterface.GetDogmaAttributesAttributeIdOk();
      //expect(instance).to.be();
    });

    it('should have the property defaultValue (base name: "default_value")', function() {
      // uncomment below and update the code to test the property defaultValue
      //var instane = new EveSwaggerInterface.GetDogmaAttributesAttributeIdOk();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new EveSwaggerInterface.GetDogmaAttributesAttributeIdOk();
      //expect(instance).to.be();
    });

    it('should have the property displayName (base name: "display_name")', function() {
      // uncomment below and update the code to test the property displayName
      //var instane = new EveSwaggerInterface.GetDogmaAttributesAttributeIdOk();
      //expect(instance).to.be();
    });

    it('should have the property highIsGood (base name: "high_is_good")', function() {
      // uncomment below and update the code to test the property highIsGood
      //var instane = new EveSwaggerInterface.GetDogmaAttributesAttributeIdOk();
      //expect(instance).to.be();
    });

    it('should have the property iconId (base name: "icon_id")', function() {
      // uncomment below and update the code to test the property iconId
      //var instane = new EveSwaggerInterface.GetDogmaAttributesAttributeIdOk();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new EveSwaggerInterface.GetDogmaAttributesAttributeIdOk();
      //expect(instance).to.be();
    });

    it('should have the property published (base name: "published")', function() {
      // uncomment below and update the code to test the property published
      //var instane = new EveSwaggerInterface.GetDogmaAttributesAttributeIdOk();
      //expect(instance).to.be();
    });

    it('should have the property stackable (base name: "stackable")', function() {
      // uncomment below and update the code to test the property stackable
      //var instane = new EveSwaggerInterface.GetDogmaAttributesAttributeIdOk();
      //expect(instance).to.be();
    });

    it('should have the property unitId (base name: "unit_id")', function() {
      // uncomment below and update the code to test the property unitId
      //var instane = new EveSwaggerInterface.GetDogmaAttributesAttributeIdOk();
      //expect(instance).to.be();
    });

  });

}));
