/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveSwaggerInterface);
  }
}(this, function(expect, EveSwaggerInterface) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EveSwaggerInterface.GetKillmailsKillmailIdKillmailHashItem1();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetKillmailsKillmailIdKillmailHashItem1', function() {
    it('should create an instance of GetKillmailsKillmailIdKillmailHashItem1', function() {
      // uncomment below and update the code to test GetKillmailsKillmailIdKillmailHashItem1
      //var instane = new EveSwaggerInterface.GetKillmailsKillmailIdKillmailHashItem1();
      //expect(instance).to.be.a(EveSwaggerInterface.GetKillmailsKillmailIdKillmailHashItem1);
    });

    it('should have the property flag (base name: "flag")', function() {
      // uncomment below and update the code to test the property flag
      //var instane = new EveSwaggerInterface.GetKillmailsKillmailIdKillmailHashItem1();
      //expect(instance).to.be();
    });

    it('should have the property itemTypeId (base name: "item_type_id")', function() {
      // uncomment below and update the code to test the property itemTypeId
      //var instane = new EveSwaggerInterface.GetKillmailsKillmailIdKillmailHashItem1();
      //expect(instance).to.be();
    });

    it('should have the property items (base name: "items")', function() {
      // uncomment below and update the code to test the property items
      //var instane = new EveSwaggerInterface.GetKillmailsKillmailIdKillmailHashItem1();
      //expect(instance).to.be();
    });

    it('should have the property quantityDestroyed (base name: "quantity_destroyed")', function() {
      // uncomment below and update the code to test the property quantityDestroyed
      //var instane = new EveSwaggerInterface.GetKillmailsKillmailIdKillmailHashItem1();
      //expect(instance).to.be();
    });

    it('should have the property quantityDropped (base name: "quantity_dropped")', function() {
      // uncomment below and update the code to test the property quantityDropped
      //var instane = new EveSwaggerInterface.GetKillmailsKillmailIdKillmailHashItem1();
      //expect(instance).to.be();
    });

    it('should have the property singleton (base name: "singleton")', function() {
      // uncomment below and update the code to test the property singleton
      //var instane = new EveSwaggerInterface.GetKillmailsKillmailIdKillmailHashItem1();
      //expect(instance).to.be();
    });

  });

}));
