/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveSwaggerInterface);
  }
}(this, function(expect, EveSwaggerInterface) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EveSwaggerInterface.GetLoyaltyStoresCorporationIdOffers200Ok();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetLoyaltyStoresCorporationIdOffers200Ok', function() {
    it('should create an instance of GetLoyaltyStoresCorporationIdOffers200Ok', function() {
      // uncomment below and update the code to test GetLoyaltyStoresCorporationIdOffers200Ok
      //var instane = new EveSwaggerInterface.GetLoyaltyStoresCorporationIdOffers200Ok();
      //expect(instance).to.be.a(EveSwaggerInterface.GetLoyaltyStoresCorporationIdOffers200Ok);
    });

    it('should have the property iskCost (base name: "isk_cost")', function() {
      // uncomment below and update the code to test the property iskCost
      //var instane = new EveSwaggerInterface.GetLoyaltyStoresCorporationIdOffers200Ok();
      //expect(instance).to.be();
    });

    it('should have the property lpCost (base name: "lp_cost")', function() {
      // uncomment below and update the code to test the property lpCost
      //var instane = new EveSwaggerInterface.GetLoyaltyStoresCorporationIdOffers200Ok();
      //expect(instance).to.be();
    });

    it('should have the property offerId (base name: "offer_id")', function() {
      // uncomment below and update the code to test the property offerId
      //var instane = new EveSwaggerInterface.GetLoyaltyStoresCorporationIdOffers200Ok();
      //expect(instance).to.be();
    });

    it('should have the property quantity (base name: "quantity")', function() {
      // uncomment below and update the code to test the property quantity
      //var instane = new EveSwaggerInterface.GetLoyaltyStoresCorporationIdOffers200Ok();
      //expect(instance).to.be();
    });

    it('should have the property requiredItems (base name: "required_items")', function() {
      // uncomment below and update the code to test the property requiredItems
      //var instane = new EveSwaggerInterface.GetLoyaltyStoresCorporationIdOffers200Ok();
      //expect(instance).to.be();
    });

    it('should have the property typeId (base name: "type_id")', function() {
      // uncomment below and update the code to test the property typeId
      //var instane = new EveSwaggerInterface.GetLoyaltyStoresCorporationIdOffers200Ok();
      //expect(instance).to.be();
    });

  });

}));
