/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveSwaggerInterface);
  }
}(this, function(expect, EveSwaggerInterface) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EveSwaggerInterface.GetUniverseSystemsSystemIdOk();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetUniverseSystemsSystemIdOk', function() {
    it('should create an instance of GetUniverseSystemsSystemIdOk', function() {
      // uncomment below and update the code to test GetUniverseSystemsSystemIdOk
      //var instane = new EveSwaggerInterface.GetUniverseSystemsSystemIdOk();
      //expect(instance).to.be.a(EveSwaggerInterface.GetUniverseSystemsSystemIdOk);
    });

    it('should have the property constellationId (base name: "constellation_id")', function() {
      // uncomment below and update the code to test the property constellationId
      //var instane = new EveSwaggerInterface.GetUniverseSystemsSystemIdOk();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new EveSwaggerInterface.GetUniverseSystemsSystemIdOk();
      //expect(instance).to.be();
    });

    it('should have the property planets (base name: "planets")', function() {
      // uncomment below and update the code to test the property planets
      //var instane = new EveSwaggerInterface.GetUniverseSystemsSystemIdOk();
      //expect(instance).to.be();
    });

    it('should have the property position (base name: "position")', function() {
      // uncomment below and update the code to test the property position
      //var instane = new EveSwaggerInterface.GetUniverseSystemsSystemIdOk();
      //expect(instance).to.be();
    });

    it('should have the property securityClass (base name: "security_class")', function() {
      // uncomment below and update the code to test the property securityClass
      //var instane = new EveSwaggerInterface.GetUniverseSystemsSystemIdOk();
      //expect(instance).to.be();
    });

    it('should have the property securityStatus (base name: "security_status")', function() {
      // uncomment below and update the code to test the property securityStatus
      //var instane = new EveSwaggerInterface.GetUniverseSystemsSystemIdOk();
      //expect(instance).to.be();
    });

    it('should have the property stargates (base name: "stargates")', function() {
      // uncomment below and update the code to test the property stargates
      //var instane = new EveSwaggerInterface.GetUniverseSystemsSystemIdOk();
      //expect(instance).to.be();
    });

    it('should have the property systemId (base name: "system_id")', function() {
      // uncomment below and update the code to test the property systemId
      //var instane = new EveSwaggerInterface.GetUniverseSystemsSystemIdOk();
      //expect(instance).to.be();
    });

  });

}));
