/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveSwaggerInterface);
  }
}(this, function(expect, EveSwaggerInterface) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EveSwaggerInterface.GetUniverseSystemKills200Ok();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetUniverseSystemKills200Ok', function() {
    it('should create an instance of GetUniverseSystemKills200Ok', function() {
      // uncomment below and update the code to test GetUniverseSystemKills200Ok
      //var instane = new EveSwaggerInterface.GetUniverseSystemKills200Ok();
      //expect(instance).to.be.a(EveSwaggerInterface.GetUniverseSystemKills200Ok);
    });

    it('should have the property npcKills (base name: "npc_kills")', function() {
      // uncomment below and update the code to test the property npcKills
      //var instane = new EveSwaggerInterface.GetUniverseSystemKills200Ok();
      //expect(instance).to.be();
    });

    it('should have the property podKills (base name: "pod_kills")', function() {
      // uncomment below and update the code to test the property podKills
      //var instane = new EveSwaggerInterface.GetUniverseSystemKills200Ok();
      //expect(instance).to.be();
    });

    it('should have the property shipKills (base name: "ship_kills")', function() {
      // uncomment below and update the code to test the property shipKills
      //var instane = new EveSwaggerInterface.GetUniverseSystemKills200Ok();
      //expect(instance).to.be();
    });

    it('should have the property systemId (base name: "system_id")', function() {
      // uncomment below and update the code to test the property systemId
      //var instane = new EveSwaggerInterface.GetUniverseSystemKills200Ok();
      //expect(instance).to.be();
    });

  });

}));
