/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveSwaggerInterface);
  }
}(this, function(expect, EveSwaggerInterface) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EveSwaggerInterface.GetUniverseGraphicsGraphicIdOk();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetUniverseGraphicsGraphicIdOk', function() {
    it('should create an instance of GetUniverseGraphicsGraphicIdOk', function() {
      // uncomment below and update the code to test GetUniverseGraphicsGraphicIdOk
      //var instane = new EveSwaggerInterface.GetUniverseGraphicsGraphicIdOk();
      //expect(instance).to.be.a(EveSwaggerInterface.GetUniverseGraphicsGraphicIdOk);
    });

    it('should have the property collisionFile (base name: "collision_file")', function() {
      // uncomment below and update the code to test the property collisionFile
      //var instane = new EveSwaggerInterface.GetUniverseGraphicsGraphicIdOk();
      //expect(instance).to.be();
    });

    it('should have the property graphicFile (base name: "graphic_file")', function() {
      // uncomment below and update the code to test the property graphicFile
      //var instane = new EveSwaggerInterface.GetUniverseGraphicsGraphicIdOk();
      //expect(instance).to.be();
    });

    it('should have the property graphicId (base name: "graphic_id")', function() {
      // uncomment below and update the code to test the property graphicId
      //var instane = new EveSwaggerInterface.GetUniverseGraphicsGraphicIdOk();
      //expect(instance).to.be();
    });

    it('should have the property iconFolder (base name: "icon_folder")', function() {
      // uncomment below and update the code to test the property iconFolder
      //var instane = new EveSwaggerInterface.GetUniverseGraphicsGraphicIdOk();
      //expect(instance).to.be();
    });

    it('should have the property sofDna (base name: "sof_dna")', function() {
      // uncomment below and update the code to test the property sofDna
      //var instane = new EveSwaggerInterface.GetUniverseGraphicsGraphicIdOk();
      //expect(instance).to.be();
    });

    it('should have the property sofFationName (base name: "sof_fation_name")', function() {
      // uncomment below and update the code to test the property sofFationName
      //var instane = new EveSwaggerInterface.GetUniverseGraphicsGraphicIdOk();
      //expect(instance).to.be();
    });

    it('should have the property sofHullName (base name: "sof_hull_name")', function() {
      // uncomment below and update the code to test the property sofHullName
      //var instane = new EveSwaggerInterface.GetUniverseGraphicsGraphicIdOk();
      //expect(instance).to.be();
    });

    it('should have the property sofRaceName (base name: "sof_race_name")', function() {
      // uncomment below and update the code to test the property sofRaceName
      //var instane = new EveSwaggerInterface.GetUniverseGraphicsGraphicIdOk();
      //expect(instance).to.be();
    });

  });

}));
