/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveSwaggerInterface);
  }
}(this, function(expect, EveSwaggerInterface) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EveSwaggerInterface.CorporationApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CorporationApi', function() {
    describe('getCorporationsCorporationId', function() {
      it('should call getCorporationsCorporationId successfully', function(done) {
        //uncomment below and update the code to test getCorporationsCorporationId
        //instance.getCorporationsCorporationId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCorporationsCorporationIdAlliancehistory', function() {
      it('should call getCorporationsCorporationIdAlliancehistory successfully', function(done) {
        //uncomment below and update the code to test getCorporationsCorporationIdAlliancehistory
        //instance.getCorporationsCorporationIdAlliancehistory(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCorporationsCorporationIdIcons', function() {
      it('should call getCorporationsCorporationIdIcons successfully', function(done) {
        //uncomment below and update the code to test getCorporationsCorporationIdIcons
        //instance.getCorporationsCorporationIdIcons(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCorporationsCorporationIdMembers', function() {
      it('should call getCorporationsCorporationIdMembers successfully', function(done) {
        //uncomment below and update the code to test getCorporationsCorporationIdMembers
        //instance.getCorporationsCorporationIdMembers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCorporationsCorporationIdRoles', function() {
      it('should call getCorporationsCorporationIdRoles successfully', function(done) {
        //uncomment below and update the code to test getCorporationsCorporationIdRoles
        //instance.getCorporationsCorporationIdRoles(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCorporationsCorporationIdStructures', function() {
      it('should call getCorporationsCorporationIdStructures successfully', function(done) {
        //uncomment below and update the code to test getCorporationsCorporationIdStructures
        //instance.getCorporationsCorporationIdStructures(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCorporationsNames', function() {
      it('should call getCorporationsNames successfully', function(done) {
        //uncomment below and update the code to test getCorporationsNames
        //instance.getCorporationsNames(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCorporationsNpccorps', function() {
      it('should call getCorporationsNpccorps successfully', function(done) {
        //uncomment below and update the code to test getCorporationsNpccorps
        //instance.getCorporationsNpccorps(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putCorporationsCorporationIdStructuresStructureId', function() {
      it('should call putCorporationsCorporationIdStructuresStructureId successfully', function(done) {
        //uncomment below and update the code to test putCorporationsCorporationIdStructuresStructureId
        //instance.putCorporationsCorporationIdStructuresStructureId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
