/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveSwaggerInterface);
  }
}(this, function(expect, EveSwaggerInterface) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EveSwaggerInterface.MarketApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MarketApi', function() {
    describe('getCharactersCharacterIdOrders', function() {
      it('should call getCharactersCharacterIdOrders successfully', function(done) {
        //uncomment below and update the code to test getCharactersCharacterIdOrders
        //instance.getCharactersCharacterIdOrders(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMarketsGroups', function() {
      it('should call getMarketsGroups successfully', function(done) {
        //uncomment below and update the code to test getMarketsGroups
        //instance.getMarketsGroups(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMarketsGroupsMarketGroupId', function() {
      it('should call getMarketsGroupsMarketGroupId successfully', function(done) {
        //uncomment below and update the code to test getMarketsGroupsMarketGroupId
        //instance.getMarketsGroupsMarketGroupId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMarketsPrices', function() {
      it('should call getMarketsPrices successfully', function(done) {
        //uncomment below and update the code to test getMarketsPrices
        //instance.getMarketsPrices(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMarketsRegionIdHistory', function() {
      it('should call getMarketsRegionIdHistory successfully', function(done) {
        //uncomment below and update the code to test getMarketsRegionIdHistory
        //instance.getMarketsRegionIdHistory(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMarketsRegionIdOrders', function() {
      it('should call getMarketsRegionIdOrders successfully', function(done) {
        //uncomment below and update the code to test getMarketsRegionIdOrders
        //instance.getMarketsRegionIdOrders(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMarketsStructuresStructureId', function() {
      it('should call getMarketsStructuresStructureId successfully', function(done) {
        //uncomment below and update the code to test getMarketsStructuresStructureId
        //instance.getMarketsStructuresStructureId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
